name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: |
          docker build -t frontend-app:latest ./frontend
          docker build -t backend-app:latest ./backend

      - name: Run Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Load Docker Images into Minikube
        run: |
          minikube image load frontend-app:latest
          minikube image load backend-app:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl get pods -A

  deploy-to-ibm-cloud:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry kubernetes-service

      - name: Authenticate with IBM Cloud
        run: |
          ibmcloud login -a https://cloud.ibm.com -u passcode -p zc6F2sQu2R
          ibmcloud cr region-set global

      - name: Push Docker Images to IBM Cloud Registry
        run: |
          docker tag frontend-app:latest icr.io/phase-3-att3/frontend-app:latest
          docker tag backend-app:latest icr.io/phase-3-att3/backend-app:latest
          docker push icr.io/phase-3-att3/frontend-app:latest
          docker push icr.io/phase-3-att3/backend-app:latest

      - name: Deploy to IBM Kubernetes Service
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl get pods -A
